// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  //menu da appbar
  static const IconData menu =
      IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //filtro de pets
  static const IconData switch_icon =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //pets
  static const IconData bird =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //coração
  static const IconData favorite =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_border =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //localização
  static const IconData location =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //seta pra esquerda da página do pet
  static const IconData left_open =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //pata
  static const IconData paw =
      IconData(0xf1b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //símbolo feminino
  static const IconData venus =
      IconData(0xf221, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  //símbolo masculino
  static const IconData mars =
      IconData(0xf222, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///